### ISSUE TITLE
Possibility to run two deck-chores containers in parallel

### ISSUE THREAD

**Issue by joaomvfsantos** [funkyfuture/deck-chores#19]
Do you plan on supporting two deck-chores containers in parallel in the near future? Right now I'm getting the "There's another container running deck-chores, maybe paused or restarting." error message

**Comment by funkyfuture** [comment]
one could optionally disable these checks. but what would be a use-case?

**Comment by joaomvfsantos** [comment]
For me I have the need to run staging and production code in the same machine (unfortunately this is out of my control). I have docker compose configurations for both staging and production, each of them starting a deck-chores container to keep things separated, and thus getting this error. I could probably get around this by running only one container of docker-chores where both my production and staging cron job scripts would run, but i guess the cleanest way would be to keep everything separated. Was there a strong reason to have this check in the first place?

**Comment by funkyfuture** [comment]
yes, the reason is simply that multiple deck-chores instances would each run any job. that is not desirable.

the concept is not to run one deck-chores instance per project, but to have one for all.

if the docs suggest somehow that running multiple instances would be a good idea, that should be fixed.
