### ISSUE TITLE
Leave output in executing container

### ISSUE THREAD

**Issue by umulmrum** [funkyfuture/deck-chores#32]
Hi,

by default, any output the executed tasks produce will be collected by deck-chores and output at the end of an execution. What I would instead like is that output is left as if the job was executed directly in the target container (so that the application log is not divided between two containers).
Is there an option for that (or am I doing anything wrong? Using deck-chores together with docker-compose)?

Thanks for your work!

**Comment by funkyfuture** [comment]
this is roughly the relevant stuff that happens when the `exec` endpoint is used (as `deck-chores` does to run jobs in containers):

- allocate a pseudo-tty
- invoke a process attached to that tty
- return the output of the tty to the client

therefore you can write the output to a file in the container, e.g. by smple redirection or with with `tee`. but afaik there's no way to redirect to the tty to the one that is attached to the main process of a container. maybe this could be achieved by writing to a special file in the container's `/dev` folder.

**Comment by funkyfuture** [comment]
@umulmrum have you tried this idea?

> maybe this could be achieved by writing to a special file in the container's `/dev` folder.

**Comment by umulmrum** [comment]
@funkyfuture Ah sorry, didn't check that. I ended up logging to a regular file instead, as stdout was too problematic (using PHP-FPM, where stdout is a bit awkward anyway). Maybe I'll try again in some time -  thank you for supporting :-)

**Comment by funkyfuture** [comment]
closing this, as a hint is added to the docs for the next release: 737aa46902aa81d3aaaf47d67c5c2cac74396b5f

**Comment by Sadrak** [comment]
I am starting with deck-chores and have kind of identical output from different jobs on different containers. Is it possible to prefix the output at least by the containername perhaps?

**Comment by funkyfuture** [comment]
i recommend to log "into" the container that executes the job. see my previous post in this thread.
