### ISSUE TITLE
hub.docker.com images seems out of date

### ISSUE THREAD

**Issue by Silex** [funkyfuture/deck-chores#87]
Hello,

https://hub.docker.com/r/funkyfuture/deck-chores/tags sorted by "newest" show that images were pushed 10 months ago, and for example tag "1" is severly out of date.

Image at https://github.com/funkyfuture/deck-chores/pkgs/container/deck-chores looks more up to date.

Also, the lack of "latest" tag is annoying, as said by many people in #49 and #50.

**Comment by funkyfuture** [comment]
the `1` tag is two months old there. the build pipeline is struggling with reliability issues, and therefore the images aren't as up-to-date as they could be. currently i hope that the GH Actions will be improving to address the reliability.

i'd generally recommend to pull the images from ghcr.io, and to build images in your infrastructure for the latest releases when these are outdated.

there will be no `latest` tag in order to not annoy other people with breaking changes.
